### ISSUE TITLE
How to use it 

### ISSUE THREAD

**Issue by rockyzhengwu** [mauvilsa/nw-page-editor#2]
I download the sdk version and  run ./nwjs 
<img width="1299" alt="屏幕快照 2019-03-11 上午10 21 06" src="https://user-images.githubusercontent.com/10402091/54096606-8470c480-43e7-11e9-8b04-bb1fda542199.png">
but i don't know how to use it , shortcuts not work

**Comment by mauvilsa** [comment]
@rockyzhengwu now reading the installation instructions I see that I must have updated it and did not make the usage very clear. I am currently traveling so it is hard for me to fix the readme. But I can help you through this issue.

I guess you are either using linux or mac, since in windows I think the executable is nw.exe and you were mentioning nwjs. If this is the case and you did follow the installation instructions, adding to your PATH both the directory containing nwjs and the bin directory of the repo that contains the nw-page-editor executable. If you did this correctly then you should be able to run the nw-page-editor command from any directory. If run without any arguments the app opens and you can then you can ctrl+o to select a page xml to open. Though most of the times it is more convenient to specify the files/directory to open from the command line. See the synopsis section.

**Comment by rockyzhengwu** [comment]
Thanks for you help .  

I'm using mac , I had added PATH like below:
```
export PATH=$PATH:/Users/zhengwu/Downloads/nwjs-sdk-v0.36.4-osx-x64/nwjs.app/Contents/MacOS
export PATH=$PATH:/Users/zhengwu/workspace/Github/nw-page-editor/bin
```
but the shortcuts dosen't work !

**Comment by mauvilsa** [comment]
I am not sure what you mean by "the shortcuts doesn't work". Do you mean that when you execute the nw-page-editor command the app doesn't open? There is no error message? Is a file /tmp/nw-page-editor.log created? If so what is its content?

**Comment by rockyzhengwu** [comment]
ctrl/cmd + o  nothing happen  only a warning 
```
2019-03-11 14:36:57.587 nwjs[83530:32058017] *** WARNING: Textured window <NativeWidgetMacNSWindow: 0x7f9233d40630> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

**Comment by mauvilsa** [comment]
But is this the content of /tmp/nw-page-editor.log? The nw-page-editor command does not work?

Try to open directly an xml from the examples directory, i.e.

    cd /Users/zhengwu/workspace/Github/nw-page-editor/
    nw-page-editor ./examples/lorem.xml

**Comment by rockyzhengwu** [comment]
in bin/nw-page-editor line 23 i think  should be:
```
nw=$(mdfind nwjs.app | head -n 1)"/Contents/MacOS/nwjs";
```
I fix the line and can open the example , but ctrl/cmd+o  also nothing happen
```
cd /Users/zhengwu/workspace/Github/nw-page-editor/
./bin/nw-page-editor ./examples/lorem.xml
```

**Comment by rockyzhengwu** [comment]
<img width="548" alt="屏幕快照 2019-03-11 下午3 23 29" src="https://user-images.githubusercontent.com/10402091/54106612-ac751d80-4411-11e9-92f1-33891252efd7.png">

I can use this by open the example first , thanks for you help

**Comment by mauvilsa** [comment]
@rockyzhengwu I have fixed the bug in bin/nw-page-editor you commented before and improved the readme to make it more clear how to use the app.
