### ISSUE TITLE
Convert pdf to page-xml

### ISSUE THREAD

**Issue by ghost** [mauvilsa/nw-page-editor#3]
On 2019/09/01 23:02, deepseek wrote:
>
> @mauvilsa Thank you for your hard word,
>
> Is there a way to convert a pdf file into a page-xml file.
> perhaps convert the pdf to svg first, then to page-xml?

**Comment by mauvilsa** [comment]
On 2019/09/02 17:24, deepseek wrote:
>
> @mauvilsa Thank you for replying soon,
> The Issue:
>
> Currently, I am working on creating a text-line detection model, using toolkits like P2PaLA.
> The issue is that in-order to create a state-of-the-art model that is sophisticated enough, I would need a large amount of training data and time.
> The Solution:
>
> Here is where the pdf2page-xml come handy, it would allow creating a huge ground-truth input so fast, using fully digital pdf files, which can be used in training.
> The concept:
>
> https://github.com/lvoegtlin/svg_to_page
> https://github.com/kermitt2/pdfalto
>
> Conclusion:
> For now, I am interested in converting pdf files into page-xml with Text-Lines.
> The near future, convert pdf into page-xml files with Lines & Images to train a layout analysis model.
>
> Waiting for your reply

@deepseek It all depends on what kind of pdf you are interested in. Is it a purely digital pdf? Is it just images of (scanned) pages? Is it a mixture of both digital and images that might contain text?

In all of the cases you could ocr the document, for example using https://github.com/mauvilsa/tesseract-recognize which directly outputs page xml. There are other ocr engines that can output alto format (e.g. abbyy), and these could be imported by nw-page-editor. The main drawback with ocr is that they make mistakes and if the original pdf was digital already then this is already known information that gets lost.

If the pdf is purely digital you could use pdflib TET to get a tetml xml which would then be possible to import into nw-page-editor. Though this is not free. I have wanted to develop a tool based on pdfbox to convert digital pdfs to page xml, but haven't had the time to do it.

Let me know a bit more about your needs to see if I can help a bit more.

**Comment by deepseek** [comment]
@mauvilsa Thank you for replying soon,

### The Issue:
Currently, I am working on creating a text-line detection model, using toolkits like [P2PaLA](https://github.com/lquirosd/P2PaLA).
The issue is that in-order to create a state-of-the-art model that is sophisticated enough, I would need a large amount of training data and time.

### The Solution:
Here is where the pdf2page-xml come handy, it would allow creating a huge ground-truth input so fast, using **fully digital pdf files**, which can be used in training.

### The concept:
https://github.com/lvoegtlin/svg_to_page
https://github.com/kermitt2/pdfalto


Conclusion:
For now, I am interested in converting pdf files into page-xml with `Text-Lines`.
The near future, convert pdf into page-xml files with `Lines` & `Images` to train a layout analysis model.

Waiting for your reply

**Comment by mauvilsa** [comment]
On 2019/09/04 18:54, deepseek wrote:
>
> @mauvilsa you're smart to notice,
>
>     Currently, I have a large number of pdf files that I scraped from the internet, no svg files.
>     pdflib TET is a bit expensive.
>     pdfalto was suggested because of alto2page & prima-page-converter.
>     You were smart to notice that the pdfalto was not proper, I discovered that the hard way in the beginning when I tried: PDF > pdfalto > prima-page-converter = page-xml
>     prima-page-converter was facing difficulties, and the resulted page-xml was not opening using prima-page-viewer, so I had to modify each page-xml file manually to fix it.
>
> My goal is to convert PDF files to page-xml.
> page-xml would help greatly in creating a complex document layout analysis model.

nw-page-editor internaly represents page xmls as svg, but it is a very specific svg that resembles the original page xml. svg could be used for many purposes, so it does not really make sense to have a generic svg to page conversion. It needs to be a specific kind of svg for this to make sense. Do you have large amounts of svgs that you could use for text line detection training? How do these look like? Are these svgs obtained from pdfs using some tool? If it is somewhat a standard svg I could consider implementing an import for this format. 

Since you are interested in fully digital pdfs, then as I said, there is pdflib TET that would convert a pdf to tetml, and I could easily enable import from tetml. Though not a free tool. I also just looked at pdfalto and tried it out. I would happily add an import function for alto v3, however, that tool does not generate proper alto files. So I would not implement an import for that tool unless the output is proper alto. I created an issuer for that  https://github.com/kermitt2/pdfalto/issues/70 . Finally there is pdfbox, but that would be implementing a tool to do the conversion. Not sure if you would like to attempt implementing this.

**Comment by deepseek** [comment]
@mauvilsa you're smart to notice,

- Currently, I have a large number of pdf files that I scraped from the internet, no svg files.
- pdflib TET is a bit expensive.
- pdfalto was suggested because of [alto2page](https://github.com/mauvilsa/nw-page-editor/blob/master/xslt/alto2page.xslt) & [prima-page-converter](https://github.com/PRImA-Research-Lab/prima-page-converter).
- You were smart to notice that the pdfalto was not proper, I discovered that the hard way in the beginning when I tried: PDF > pdfalto > prima-page-converter = page-xml
prima-page-converter was facing difficulties, and the resulted page-xml was not opening using prima-page-viewer, so I had to modify each page-xml file manually to fix it.

My goal is to convert PDF files to page-xml.
page-xml would help greatly in creating a complex document layout analysis model.

**Comment by mauvilsa** [comment]
On 2019/09/05 20:31, deepseek wrote:
>
> @mauvilsa I spoke with the developer of svg_to_page, and he added an example to the repo.
> He also states:
>
>     this script converts coordinate SVG files (path-based polygons) to page XML
>
> Also, have a look ate the new issue that I opened lvoegtlin/svg_to_page#3 to validate the generated page-xml.
>
> So what do you think?

I looked at svg_to_page. But it doesn't explain much about what it does and anyway I don't have any svgs for converting to page.

**Comment by deepseek** [comment]
@mauvilsa I spoke with the developer of svg_to_page, and he added an example to the repo.
He also states:

> this script converts coordinate SVG files (path-based polygons) to page XML

Also, have a look ate the new issue that I opened lvoegtlin/svg_to_page#3 to validate the generated page-xml.

So what do you think?

**Comment by deepseek** [comment]
@mauvilsa using your version of pdfalto, the generated alto file validates successfully.
Now I want to convert the alto file to page-xml, I used prima-page-converter but it showed and error of:
```
Error writing target PAGE XML file
```
My files attached 
[test.zip](https://github.com/mauvilsa/nw-page-editor/files/3612767/test.zip)

Can you have a look into this matter, or perhaps tell me how to convert the alto xml to page-xml.

Waiting for your reply

**Comment by deepseek** [comment]
@mauvilsa
Using your version of pdfalto, the generated alto file validates successfully.
But now I am facing another issue, pdfalto generated an alto.xml with a resolution of about 72 pixels/in which resulted in an image of size Width: 595 & Height: 842 pixels. That's very small.

**Is there a way to set the resolution for pdfalto?**
Attached files 
[dpi issue.zip](https://github.com/mauvilsa/nw-page-editor/files/3613379/dpi.issue.zip)

Waiting for your reply


My commands:
```
./pdfalto -f 1 -noImage -noImageInline -blocks -readingOrder ./test.pdf ./alto.xml
gs -sDEVICE=jpeg -sOutputFile=out.jpg -dLastPage=1 test.pdf
java -jar JPageViewer.jar
```

**Comment by ghost** [comment]
Thanks man you're amazing!!!!

**Comment by mauvilsa** [comment]
@deepseek not cool that you the title and original description with a dot and removed all your comments. Please restore them.
