### ISSUE TITLE
other region types

### ISSUE THREAD

**Issue by dasch124** [mauvilsa/nw-page-editor#5]
Hi, 
if I understand correctly, the application validates against https://github.com/omni-us/pageformat/blob/fe1ca7f589dfd8aa9cc9abcc4a336e9afddd8aba/pagecontent_omnius.xsd 

I was wondering: The schema mentions several elements which I don’t find reflected in the editor’s GUI, namely ImageRegion, SeparatorRegion and CustomRegion. Especially ImageRegion would be very helpful for us. Are there plans to include these as well? Thank you!

**Comment by mauvilsa** [comment]
@dasch124 this should be in the UI now. Please check.

**Comment by dasch124** [comment]
yes, it does – thank you very much!

**Comment by dasch124** [comment]
Just another minor question on that issue (if I may ask): Given that CustomRegion may have an [optional attribute](https://github.com/omni-us/pageformat/blob/fe1ca7f589dfd8aa9cc9abcc4a336e9afddd8aba/pagecontent_omnius.xsd#L453) to specify its type – would it be much work to add a simple textbox for that as well?
Thank you for your effort!

**Comment by mauvilsa** [comment]
@dasch124 great that you are looking at the schema and asking based on this. This way your questions do relate to things that are more or less planned, so I can help. Would be good to know who you are. Maybe can you connect with me via linkedin?

I have now implemented CustoRegion with arbitrary type. Please check.

**Comment by mauvilsa** [comment]
@dasch124 did you try the CustomRegions with custom type? Can this issue be closed?

**Comment by dasch124** [comment]
hi, sorry for the delayed response and thanks for the quick response! – did you build a docker file out of it? (because we are just pulling from dockerhub and not building the application from scratch) unfortunately I’m not on linkedIn, but we you can reach me via mail (see my profile)

**Comment by mauvilsa** [comment]
@dasch124 docker hub builds automatically the docker image every time I release a version. In general I would not create a release for every commit to the repo. Testing new features should normally be done by cloning and using the desktop app or building the docker image from source.

However, for you to test this new feature you can use a docker image from docker hub. I have added some other new features and so created a release today. Be sure to read again https://github.com/mauvilsa/nw-page-editor#web-server-variant since the changes affect the URLs used to access.

**Comment by dasch124** [comment]
yes, works like a charm! thank you!
